<?xml version="1.0"?>
<package format="3">
  <name>small_car_av</name>
  <version>0.1.0</version>
  <description>小车 ROS 2 真实摄像头和麦克风采集节点。</description>
  <maintainer email="small-car@example.com">small_car</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>small_car_interfaces</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
