<?xml version="1.0"?>
<package format="3">
  <name>small_car_bridge</name>
  <version>0.1.0</version>
  <description>C30D STM32 底盘与 ROS2 之间的串口桥接节点。</description>
  <maintainer email="small-car@example.com">small_car</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>diagnostic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>
  <depend>trajectory_msgs</depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>small_car_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
